packages:
  - "packages/disact"
  - "packages/disact-engine"
  - "packages/example/*"
  - "packages/tsconfig"

catalog:
  "@types/mdast": "^4.0.4"
  "@types/node": "~22.18.6"
  "mdast-util-gfm-strikethrough": "^2.0.0"
  "mdast-util-to-markdown": "^2.1.2"
  "orval": "^7.3.0"
  "ts-dedent": "^2.2.0"
  "tsdown": "^0.16.0"
  "turbo": "^2.5.6"
  "typescript": "^5.9.2"
  "vite-node": "^3.2.4"
  "vitest": "^4.0.6"
  "oxfmt": "^0.19.0"
  "oxlint": "^1.34.0"
  "oxlint-tsgolint": "^0.10.0"
